# Generated by Django 5.1.4 on 2025-06-06 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
