# Generated by Django 5.1.4 on 2025-06-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_alter_news_postedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='updatedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
